// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKeQIRfG8aVpgmfutIyxFrFYRwEfb_xBc',
    appId: '1:535733484932:web:a47812091a8f947db6f1d1',
    messagingSenderId: '535733484932',
    projectId: 'techversenew',
    authDomain: 'techversenew.firebaseapp.com',
    storageBucket: 'techversenew.firebasestorage.app',
    measurementId: 'G-B2JPPZ8GW3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYpwFq0q8F3A7TTRpD8z-iTTZI5C-SdCc',
    appId: '1:535733484932:android:bffc0ef47dea688eb6f1d1',
    messagingSenderId: '535733484932',
    projectId: 'techversenew',
    storageBucket: 'techversenew.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwsEiWThQS8VNBJO0-8HlnNe1V7Rn49cs',
    appId: '1:535733484932:ios:d1d287ad9f3bdc1db6f1d1',
    messagingSenderId: '535733484932',
    projectId: 'techversenew',
    storageBucket: 'techversenew.firebasestorage.app',
    iosBundleId: 'com.example.techverseFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwsEiWThQS8VNBJO0-8HlnNe1V7Rn49cs',
    appId: '1:535733484932:ios:d1d287ad9f3bdc1db6f1d1',
    messagingSenderId: '535733484932',
    projectId: 'techversenew',
    storageBucket: 'techversenew.firebasestorage.app',
    iosBundleId: 'com.example.techverseFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAKeQIRfG8aVpgmfutIyxFrFYRwEfb_xBc',
    appId: '1:535733484932:web:1d3b9447e551f194b6f1d1',
    messagingSenderId: '535733484932',
    projectId: 'techversenew',
    authDomain: 'techversenew.firebaseapp.com',
    storageBucket: 'techversenew.firebasestorage.app',
    measurementId: 'G-CRP930LXZ4',
  );

}